version: '3'
services:
  ethereum:
    image: trufflesuite/ganache-cli:latest
    ports:
     - "8545:8545"
    command: "-a 10 --mnemonic 'unlock will rule rule the web'"
  button:
    depends_on:
      - unlock
    restart: always
    build:
      context: ./button
      dockerfile: ./Dockerfile
    ports:
     - "3001:80"
    volumes:
    - ./button:/usr/share/nginx/html
    - ./tests/integration/creator:/usr/share/nginx/html/test
  unlock:
    depends_on:
      - ethereum
    restart: always
    command: npm run start
    build:
      context: ./unlock
      dockerfile: ./Dockerfile
    ports:
     - "3000:3000"
    volumes:
    - ./unlock/src:/unlock/src
