version: '3'
services:
  ganache:
    restart: always
    image: trufflesuite/ganache-cli:v6.1.6
    expose:
      - 8545
    command: ["-h=0.0.0.0"]
  unlock:
    build:
      context: ..
      dockerfile: ./docker/unlock.tests.dockerfile
    depends_on:
      - ganache

